language: d
sudo: false
install:
  - ./travis_install.sh

matrix:
    include:
        - d: dmd-2.081.2
        - d: dmd-2.080.1
        - d: dmd-2.079.1
        - d: ldc-1.10.0
        - d: ldc-1.9.0
        - d: ldc-1.8.0

script:
  - dub test --build=unittest-cov --compiler=${DC}
  - dub build

after_success:
 - bash <(curl -s https://codecov.io/bash)
